### PR TITLE
Drop support for 5.2-3.6 and 6.0-3.7.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Support 6.0 on the full Python range of 3.8-3.11.
Added `python_requires` that still accepts 3.6, because I don't want to intentionally make it not installable.
    
Minor cleanup of unused files.
Fix some deprecation warnings.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@laulaz Could you review, and then merge and release?
Or grant the `collective` user access on https://pypi.org/project/collective.cookiecuttr/
Thanks!

**Comment by laulaz** [comment]
@mauritsvanrees shouldn't we fix the failing test for 5.2 / 2.7 before ?

Unfortunately, I am only maintainer on Pypi so I cannot add `collective` user (@fourdigits or @kingel maybe ?), but I can make the release myself 👍

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees shouldn't we fix the failing test for 5.2 / 2.7 before ?

Yes, I am trying.  I thought it would pass, because it works fine locally.
[Weird error](https://github.com/collective/collective.cookiecuttr/actions/runs/4415247447/jobs/7737968976#step:5:268).

Would you mind if we drop Python 2.7 support?

**Comment by laulaz** [comment]
> Would you mind if we drop Python 2.7 support?

Not at all :blush:

**Review by laulaz — APPROVED** [review]
LGTM

**Comment by mauritsvanrees** [comment]
Thanks for the review.  For me, this is ready for release.

**Comment by laulaz** [comment]
@mauritsvanrees release `2.0.0` done 👍

**Comment by mauritsvanrees** [comment]
Thanks!

**Pull request merged**
